apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-temp
spec:
  selector:
    matchLabels:
      app: convert-temp
  template:
    metadata:
      labels:
        app: convert-temp
    spec:
      containers:
      - name: convert-temp
        image: erecnovais/convert-temp:v1
        ports:
        - containerPort: 8080

---

#service web 

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
   - port: 8080
  type: LoadBalancer     